pragma ComponentBehavior: Bound
import QtQml
import QtQuick
import Quickshell.Io
import qs.modules.common
import qs.services
import "../"

NestableObject {
    id: root

    property var monitors: []
    property string pendingWorkspaceBatch: ""

    Component.onCompleted: fetchProc.running = true

    function updateMonitor(index, changes) {
        let m = root.monitors.slice()
        m[index] = Object.assign({}, m[index], changes)
        root.monitors = m
    }

    function _buildLuaLine(m) {
        if (m.disabled)
            return `hl.monitor({ output = "${m.name}", disabled = true })`

        const pos = `${m.x}x${m.y}`
        let line = `hl.monitor({ output = "${m.name}", mode = "${m.currentMode}", position = "${pos}", scale = ${m.scale}`

        if (m.transform && m.transform !== 0)
            line += `, transform = ${m.transform}`

        line += ` })`
        return line
    }

    function _buildWorkspaceRules() {
        const primaryMonitor = Config.options.hyprland.primaryMonitor ?? ""
        if (!primaryMonitor)
            return "-- Generated by Quickshell monitor settings\n"

        const workspaces = root.primaryWorkspaceNumbers()
        const lines = ["-- Generated by Quickshell monitor settings"]
        for (let i = 0; i < workspaces.length; i++)
            lines.push(`hl.workspace_rule({ workspace = "${workspaces[i]}", monitor = "${primaryMonitor}" })`)

        // Every other active monitor gets one workspace each, continuing
        // right after the primary's range (e.g. primary 1-5 -> next monitor
        // gets 6, the one after that 7, ...) - without a binding here, an
        // unbound monitor reconnecting (e.g. waking from sleep) can make
        // Hyprland improvise a workspace id instead of using a real one.
        let nextWorkspace = root.primaryWorkspaceRange().end + 1
        const otherMonitors = root._activeMonitorNames().filter(name => name !== primaryMonitor)
        for (const name of otherMonitors) {
            lines.push(`hl.workspace_rule({ workspace = "${nextWorkspace}", monitor = "${name}" })`)
            nextWorkspace++
        }

        return lines.join("\n")
    }

    function primaryWorkspaceRange() {
        const rawStart = Config.options.hyprland.primaryWorkspaceStart ?? 1
        const rawEnd = Config.options.hyprland.primaryWorkspaceEnd ?? 1
        const start = Math.max(1, Math.min(100, Math.min(rawStart, rawEnd)))
        const end = Math.max(1, Math.min(100, Math.max(rawStart, rawEnd)))
        return { start, end }
    }

    function primaryWorkspaceNumbers() {
        const range = root.primaryWorkspaceRange()
        let workspaces = []
        for (let workspace = range.start; workspace <= range.end; workspace++)
            workspaces.push(workspace)
        return workspaces
    }

    function _buildPrimaryWorkspaceBatch() {
        const primaryMonitor = Config.options.hyprland.primaryMonitor ?? ""
        if (!primaryMonitor)
            return ""

        return root.primaryWorkspaceNumbers()
            .map(workspace => `dispatch moveworkspacetomonitor ${workspace} ${primaryMonitor}`)
            .join(" ; ")
    }

    function _activeMonitorNames() {
        return root.monitors
            .filter(m => !m.disabled)
            .map(m => m.name)
    }

    function ensurePrimaryMonitorIsValid() {
        const primaryMonitor = Config.options.hyprland.primaryMonitor ?? ""
        if (!primaryMonitor)
            return

        if (!root._activeMonitorNames().includes(primaryMonitor))
            Config.options.hyprland.primaryMonitor = ""
    }

    function hiddenWidgets(name) {
        const visibility = Config.options.bar.monitorVisibility ?? []
        const entry = visibility.find(item => item.name === name)
        return entry?.hiddenWidgets ?? []
    }

    function setWidgetHidden(name, widgetId, hidden) {
        let visibility = (Config.options.bar.monitorVisibility ?? []).slice()
        const index = visibility.findIndex(item => item.name === name)
        let entry = index >= 0 ? Object.assign({}, visibility[index]) : { name, hiddenWidgets: [] }
        let hiddenWidgets = (entry.hiddenWidgets ?? []).slice().filter(id => id !== widgetId)

        if (hidden)
            hiddenWidgets.push(widgetId)

        entry.hiddenWidgets = hiddenWidgets

        if (hiddenWidgets.length === 0) {
            if (index >= 0)
                visibility.splice(index, 1)
        } else if (index >= 0) {
            visibility[index] = entry
        } else {
            visibility.push(entry)
        }

        Config.options.bar.monitorVisibility = visibility
    }

    function isWidgetVisible(name, widgetId) {
        return !root.hiddenWidgets(name).includes(widgetId)
    }

    function pruneBarMonitorVisibility() {
        const activeNames = root._activeMonitorNames()
        Config.options.bar.monitorVisibility = (Config.options.bar.monitorVisibility ?? [])
            .filter(entry => activeNames.includes(entry.name))
    }

    // Generic "does this monitor show up in a screenList-style toggle" pair -
    // an empty list conventionally means "all monitors". Shared by the bar's
    // screenList (below) and anything else with the same per-monitor
    // enable/disable shape (e.g. Interface's "Show widgets on this monitor").
    function isNameInScreenList(screenList, name) {
        const list = screenList ?? []
        return list.length === 0 || list.includes(name)
    }

    function setNameInScreenList(configEntry, name, enabled) {
        const activeMonitorNames = root.monitors
            .filter(m => !m.disabled)
            .map(m => m.name)
        let screenList = (configEntry.screenList ?? []).slice()

        if (screenList.length === 0)
            screenList = activeMonitorNames.slice()
        else
            screenList = screenList.filter(monitorName => activeMonitorNames.includes(monitorName))

        if (enabled) {
            if (!screenList.includes(name))
                screenList.push(name)
        } else {
            screenList = screenList.filter(monitorName => monitorName !== name)
        }

        configEntry.screenList = screenList.length === activeMonitorNames.length ? [] : screenList
    }

    function isBarEnabled(name) {
        return root.isNameInScreenList(Config.options.bar.screenList, name)
    }

    function setBarEnabled(name, enabled) {
        root.setNameInScreenList(Config.options.bar, name, enabled)
    }

    function save() {
        if (root.monitors.length === 0) return
        if (root.monitors.some(m => !m.name)) return

        root.ensurePrimaryMonitorIsValid()
        root.pruneBarMonitorVisibility()

        const lines = root.monitors.map(m => {
            const line = root._buildLuaLine(m)
            console.log(`[MonitorConfig] saving line: "${line}"`)
            return line
        }).join("\n")

        console.log(`[MonitorConfig] full file:\n${lines}`)

        const escaped = lines.replace(/'/g, "'\\''")
        const workspaceRules = root._buildWorkspaceRules()
        const escapedWorkspaceRules = workspaceRules.replace(/'/g, "'\\''")
        root.pendingWorkspaceBatch = root._buildPrimaryWorkspaceBatch()
        saveProc.command = ["bash", "-c",
            `printf '%s\n' '${escaped}' > ~/.config/hypr/monitors.lua && printf '%s\n' '${escapedWorkspaceRules}' > ~/.config/hypr/workspaces.lua`]
        saveProc.running = true
    }

    function applyMonitor(m) {
        if (!m.name) return

        const base = `${m.name},${m.currentMode},${m.x}x${m.y},${m.scale}`
        applyProc.command = ["hyprctl", "keyword", "monitor",
            m.disabled
                ? `${m.name},disable`
                : (m.transform && m.transform !== 0)
                    ? `${base},transform,${m.transform}`
                    : base]
        applyProc.running = true
    }

    function applyAndSave(index) {
        const monitor = root.monitors[index]
        if (monitor?.disabled) {
            root.setBarEnabled(monitor.name, false)
            if ((Config.options.hyprland.primaryMonitor ?? "") === monitor.name)
                Config.options.hyprland.primaryMonitor = ""
        }

        root.applyMonitor(root.monitors[index])
        root.save()
    }

    function logicalWidth(m) {
        return (m.transform === 1 || m.transform === 3) ? m.height : m.width
    }

    function logicalHeight(m) {
        return (m.transform === 1 || m.transform === 3) ? m.width : m.height
    }

    Process {
        id: fetchProc
        command: ["hyprctl", "monitors", "all", "-j"]
        stdout: StdioCollector {
            onStreamFinished: {
                try {
                    root.monitors = JSON.parse(text).map(m => ({
                        name:          m.name,
                        description:   m.description,
                        width:         m.width,
                        height:        m.height,
                        refreshRate:   m.refreshRate,
                        x:             m.x,
                        y:             m.y,
                        scale:         m.scale,
                        transform:     m.transform ?? 0,
                        disabled:      m.disabled,
                        availableModes: m.availableModes,
                        currentMode:   `${m.width}x${m.height}@${m.refreshRate.toFixed(2)}Hz`
                    }))
                } catch(e) {
                    console.log("[MonitorConfig] Error parseando JSON:", e)
                }
            }
        }
    }

    Process { id: applyProc }

    Process {
        id: saveProc
        onRunningChanged: if (!running) reloadProc.running = true
    }

    Process {
        id: reloadProc
        command: ["hyprctl", "reload"]
        onRunningChanged: {
            if (running) return
            if (root.pendingWorkspaceBatch.length === 0) return
            primaryWorkspaceProc.command = ["hyprctl", "--batch", root.pendingWorkspaceBatch]
            root.pendingWorkspaceBatch = ""
            primaryWorkspaceProc.running = true
        }
    }

    Process { id: primaryWorkspaceProc }
}