#!/usr/bin/env python3
"""
Lets the shell rebind - or fully disable - any named top-level Hyprland
keybind, including ones generated inside Lua for-loops (workspace numbers,
arrow-key focus/move, ...).

hyprland/keybinds.lua is actually *executed* by a real Lua interpreter
(keybind_extract.lua) with a stub `hl` table that records every hl.bind()
call fully resolved (loop variables, string concatenation, everything) -
we never try to re-implement Lua's evaluation semantics in Python. We only
ever write to a clearly marked, auto-generated block appended at the end of
custom/keybinds.lua; hyprland/keybinds.lua (template, overwritten on
dots-hyprland updates) and the user's own lines in custom/keybinds.lua are
never touched.

Rebinding a shortcut emits hl.unbind(oldKey) followed by hl.bind(newKey, ...)
for every line that shared the old key. Disabling one just emits the
hl.unbind() with no replacement bind.
"""
import argparse
import json
import os
import re
import secrets
import shutil
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
EXTRACTOR_PATH = os.path.join(SCRIPT_DIR, "keybind_extract.lua")

BEGIN_MARK = "-- ===== BEGIN illogical-impulse keybind rebinds (auto-generated by Settings > Keybinds; do not edit by hand) ====="
END_MARK = "-- ===== END illogical-impulse keybind rebinds ====="

IDENT_CHARS = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_")
DESCRIPTION_RE = re.compile(r'description\s*=\s*"((?:[^"\\]|\\.)*)"')
HEADING_RE = re.compile(r"^\s*(-+#+)!\s*(.*)")

LUA_ESCAPES = {"n": "\n", "t": "\t", "r": "\r", '"': '"', "'": "'", "\\": "\\"}


def expand(path: str) -> str:
    return os.path.expanduser(os.path.expandvars(path))


def unescape_lua(s: str) -> str:
    out = []
    i = 0
    while i < len(s):
        if s[i] == "\\" and i + 1 < len(s):
            out.append(LUA_ESCAPES.get(s[i + 1], s[i + 1]))
            i += 2
        else:
            out.append(s[i])
            i += 1
    return "".join(out)


def lua_quote(s: str) -> str:
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def mask(text: str) -> str:
    """Same-length copy of text with string/comment contents blanked to
    spaces, so keyword/bracket scanning never looks inside them."""
    out = list(text)
    i = 0
    n = len(text)
    while i < n:
        c = text[i]
        if text.startswith("--[[", i):
            end = text.find("]]", i + 4)
            end = n if end == -1 else end + 2
            for j in range(i, end):
                if out[j] != "\n":
                    out[j] = " "
            i = end
            continue
        if c == "-" and i + 1 < n and text[i + 1] == "-":
            end = text.find("\n", i)
            end = n if end == -1 else end
            for j in range(i, end):
                out[j] = " "
            i = end
            continue
        if c == '"' or c == "'":
            quote = c
            j = i + 1
            while j < n and text[j] != quote:
                if text[j] == "\\" and j + 1 < n:
                    j += 2
                else:
                    j += 1
            j = min(j + 1, n)
            for k in range(i + 1, j - 1):
                out[k] = " "
            i = j
            continue
        i += 1
    return "".join(out)


def find_closure_source(text: str, masked: str, closure_line: int) -> str:
    """Extract the verbatim `function ... end` block whose `function`
    keyword starts on the given 1-based line number."""
    lines = text.split("\n")
    offset = sum(len(l) + 1 for l in lines[:closure_line - 1])
    start = masked.find("function", offset)
    if start == -1:
        raise ValueError(f"could not locate closure starting at line {closure_line}")

    def is_word(pos, word):
        end = pos + len(word)
        if masked[pos:end] != word:
            return False
        if pos > 0 and masked[pos - 1] in IDENT_CHARS:
            return False
        if end < len(masked) and masked[end] in IDENT_CHARS:
            return False
        return True

    depth = 0
    i = start
    n = len(masked)
    while i < n:
        if is_word(i, "function"):
            depth += 1
            i += len("function")
            continue
        if is_word(i, "end"):
            depth -= 1
            i += len("end")
            if depth == 0:
                return text[start:i]
            continue
        i += 1
    raise ValueError(f"unbalanced function/end near line {closure_line}")


def substitute_upvalues(closure_text: str, upvalues: dict) -> str:
    """Replace whole-word references to captured loop upvalues (e.g. the
    `i` in a `for i = 1, 10 do ... end` loop) with their resolved Lua
    source value, so a copied closure body is self-contained."""
    if not upvalues:
        return closure_text
    masked = mask(closure_text)
    out = []
    i = 0
    n = len(closure_text)
    while i < n:
        ch = masked[i]
        if ch.isalpha() or ch == "_":
            j = i
            while j < n and masked[j] in IDENT_CHARS:
                j += 1
            word = closure_text[i:j]
            if word in upvalues:
                out.append(upvalues[word])
            else:
                out.append(word)
            i = j
            continue
        out.append(closure_text[i])
        i += 1
    return "".join(out)


def sections_by_line(text: str):
    result = {}
    current = "Other"
    for lineno, line in enumerate(text.splitlines(), start=1):
        m = HEADING_RE.match(line)
        if m and m.group(1).count("#") == 2:
            current = m.group(2).strip() or "Other"
        result[lineno] = current
    return result


def run_extractor(lib_path: str, vars_path: str, hypr_path: str, lua_bin: str):
    try:
        proc = subprocess.run(
            [lua_bin, EXTRACTOR_PATH, lib_path, vars_path, hypr_path],
            capture_output=True, text=True, timeout=15,
        )
    except FileNotFoundError:
        raise RuntimeError(f"'{lua_bin}' interpreter not found")
    except subprocess.TimeoutExpired:
        raise RuntimeError("keybind_extract.lua timed out")
    if proc.returncode != 0:
        raise RuntimeError(f"keybind_extract.lua exited {proc.returncode}: {proc.stderr.strip()}")
    try:
        data = json.loads(proc.stdout)
    except json.JSONDecodeError as e:
        raise RuntimeError(f"keybind_extract.lua produced invalid JSON ({e}): {proc.stdout[:300]}")
    if not data.get("ok"):
        raise RuntimeError(f"keybind_extract.lua: {data.get('error')}")
    return data["binds"]


def parse_defaults(hypr_path: str, lib_path: str, vars_path: str, lua_bin: str):
    """Returns dict: description -> {defaultKey, section, entries:[{dispatcher, opts}]}"""
    if not os.access(hypr_path, os.R_OK):
        raise FileNotFoundError(hypr_path)
    with open(hypr_path, "r") as f:
        text = f.read()
    masked = mask(text)
    line_sections = sections_by_line(text)

    raw_binds = run_extractor(lib_path, vars_path, hypr_path, lua_bin)

    groups = {}       # key_string -> list of entries, in call order
    group_line = {}   # key_string -> first call line

    for b in raw_binds:
        if b.get("inSubmap"):
            continue
        key_string = b["key"]
        kind = b.get("dispatcherKind")
        if kind == "direct":
            dispatcher_source = b["dispatcherSource"]
        elif kind == "closure":
            closure_text = find_closure_source(text, masked, b["closureLine"])
            dispatcher_source = substitute_upvalues(closure_text, b.get("upvalues") or {})
        else:
            continue  # unknown/unsupported dispatcher shape

        opts_source = b.get("opts")
        description = None
        if opts_source:
            dm = DESCRIPTION_RE.search(opts_source)
            if dm:
                description = unescape_lua(dm.group(1))

        entry = {"dispatcher": dispatcher_source, "opts": opts_source, "description": description}
        groups.setdefault(key_string, []).append(entry)
        group_line.setdefault(key_string, b.get("callLine", 1))

    rebindable = {}
    for key_string, entries in groups.items():
        description = next((e["description"] for e in entries if e["description"]), None)
        if not description:
            continue
        lineno = group_line[key_string]
        rebindable[description] = {
            "defaultKey": key_string,
            "section": line_sections.get(lineno, "Other"),
            "entries": [{"dispatcher": e["dispatcher"], "opts": e["opts"]} for e in entries],
        }
    return rebindable


def load_state(state_path: str) -> dict:
    """Returns {"overrides": {description: {"key": str|None}}, "custom": {id: {"description","key","command"}}}"""
    empty = {"overrides": {}, "custom": {}}
    if not os.access(state_path, os.R_OK):
        return empty
    try:
        with open(state_path, "r") as f:
            data = json.load(f)
    except (json.JSONDecodeError, OSError):
        return empty
    if not isinstance(data, dict):
        return empty

    # Older formats: either a flat {description: "NEW KEY"} map, or a flat
    # {description: {"key": ...}} map with no "custom" section at all.
    if "overrides" not in data and "custom" not in data:
        overrides = {}
        for desc, value in data.items():
            if isinstance(value, str):
                overrides[desc] = {"key": value}
            elif isinstance(value, dict) and "key" in value:
                overrides[desc] = {"key": value["key"]}
        return {"overrides": overrides, "custom": {}}

    overrides = {}
    for desc, value in (data.get("overrides") or {}).items():
        if isinstance(value, dict) and "key" in value:
            overrides[desc] = {"key": value["key"]}

    custom = {}
    for cid, value in (data.get("custom") or {}).items():
        if isinstance(value, dict) and value.get("key") and value.get("command") and value.get("description"):
            custom[cid] = {
                "description": value["description"],
                "key": value["key"],
                "command": value["command"],
                # "shell" (default): command is a shell string run via hl.dsp.exec_cmd.
                # "lua": command is verbatim Lua source used as the dispatcher itself
                # (e.g. "function() ... end" or "hl.dsp.window.move({...})"), for
                # binds that need real Hyprland state (hl.get_active_window() etc)
                # instead of shelling out.
                "kind": value.get("kind") if value.get("kind") in ("shell", "lua") else "shell",
            }
    return {"overrides": overrides, "custom": custom}


def save_state(state_path: str, state: dict):
    os.makedirs(os.path.dirname(state_path), exist_ok=True)
    with open(state_path, "w") as f:
        json.dump(state, f, indent=2, sort_keys=True)
        f.write("\n")


def strip_managed_block(content: str) -> str:
    pattern = re.compile(
        r"\n*" + re.escape(BEGIN_MARK) + r".*?" + re.escape(END_MARK) + r"\n*",
        re.DOTALL,
    )
    return pattern.sub("\n", content)


def regenerate(defaults: dict, overrides: dict, custom: dict, custom_path: str):
    # Drop overrides for descriptions that no longer resolve to a known default.
    pruned_overrides = {desc: entry for desc, entry in overrides.items() if desc in defaults}

    body_parts = []
    for desc in sorted(pruned_overrides.keys()):
        info = defaults[desc]
        old_key = info["defaultKey"]
        entry = pruned_overrides[desc]
        new_key = entry.get("key")

        if new_key is None:
            body_parts.append(f"hl.unbind({lua_quote(old_key)})  -- {desc} (disabled)")
            continue

        lines = [f"hl.unbind({lua_quote(old_key)})  -- {desc}"]
        for e in info["entries"]:
            if e["opts"]:
                lines.append(f"hl.bind({lua_quote(new_key)}, {e['dispatcher']}, {e['opts']})")
            else:
                lines.append(f"hl.bind({lua_quote(new_key)}, {e['dispatcher']})")
        body_parts.append("\n".join(lines))

    for cid in sorted(custom.keys()):
        entry = custom[cid]
        opts = f'{{ description = {lua_quote(entry["description"])} }}'
        if entry.get("kind") == "lua":
            dispatcher = entry["command"]  # verbatim Lua source, e.g. "function() ... end"
        else:
            dispatcher = f'hl.dsp.exec_cmd({lua_quote(entry["command"])})'
        line = f"hl.bind({lua_quote(entry['key'])}, {dispatcher}, {opts})  -- custom:{cid}"
        body_parts.append(line)

    existing = ""
    if os.access(custom_path, os.R_OK):
        with open(custom_path, "r") as f:
            existing = f.read()
    stripped = strip_managed_block(existing).rstrip()

    if body_parts:
        block = BEGIN_MARK + "\n\n" + "\n\n".join(body_parts) + "\n\n" + END_MARK
        new_content = (stripped + "\n\n" + block + "\n") if stripped else (block + "\n")
    else:
        new_content = stripped + "\n" if stripped else ""

    os.makedirs(os.path.dirname(custom_path), exist_ok=True)
    if os.access(custom_path, os.R_OK):
        shutil.copyfile(custom_path, custom_path + ".bak")
    with open(custom_path, "w") as f:
        f.write(new_content)

    return pruned_overrides


def cmd_list(args):
    defaults = parse_defaults(args.hypr_path, args.lib_path, args.vars_path, args.lua_bin)
    state = load_state(args.state_path)
    overrides = state["overrides"]
    keybinds = []
    for desc, info in defaults.items():
        override = overrides.get(desc)
        if override is None:
            current, disabled, overridden = info["defaultKey"], False, False
        elif override.get("key") is None:
            current, disabled, overridden = None, True, True
        else:
            current, disabled, overridden = override["key"], False, override["key"] != info["defaultKey"]
        keybinds.append({
            "description": desc,
            "section": info["section"],
            "defaultKey": info["defaultKey"],
            "currentKey": current,
            "disabled": disabled,
            "overridden": overridden,
        })
    keybinds.sort(key=lambda k: (k["section"], k["description"]))

    custom = [
        {
            "id": cid,
            "description": e["description"],
            "key": e["key"],
            "command": e["command"],
            "kind": e["kind"],
            "section": e["description"].split(":", 1)[0].strip() if ":" in e["description"] else "Custom",
        }
        for cid, e in state["custom"].items()
    ]
    custom.sort(key=lambda c: c["description"])

    print(json.dumps({"ok": True, "keybinds": keybinds, "custom": custom}))


def cmd_set(args):
    defaults = parse_defaults(args.hypr_path, args.lib_path, args.vars_path, args.lua_bin)
    if args.description not in defaults:
        print(json.dumps({"ok": False, "error": f"Unknown keybind: {args.description}"}))
        return
    state = load_state(args.state_path)
    new_key = args.key.strip()
    if new_key == defaults[args.description]["defaultKey"]:
        state["overrides"].pop(args.description, None)
    else:
        state["overrides"][args.description] = {"key": new_key}
    state["overrides"] = regenerate(defaults, state["overrides"], state["custom"], args.custom_path)
    save_state(args.state_path, state)
    print(json.dumps({"ok": True}))


def cmd_disable(args):
    defaults = parse_defaults(args.hypr_path, args.lib_path, args.vars_path, args.lua_bin)
    if args.description not in defaults:
        print(json.dumps({"ok": False, "error": f"Unknown keybind: {args.description}"}))
        return
    state = load_state(args.state_path)
    state["overrides"][args.description] = {"key": None}
    state["overrides"] = regenerate(defaults, state["overrides"], state["custom"], args.custom_path)
    save_state(args.state_path, state)
    print(json.dumps({"ok": True}))


def cmd_reset(args):
    defaults = parse_defaults(args.hypr_path, args.lib_path, args.vars_path, args.lua_bin)
    state = load_state(args.state_path)
    state["overrides"].pop(args.description, None)
    state["overrides"] = regenerate(defaults, state["overrides"], state["custom"], args.custom_path)
    save_state(args.state_path, state)
    print(json.dumps({"ok": True}))


def cmd_reset_all(args):
    defaults = parse_defaults(args.hypr_path, args.lib_path, args.vars_path, args.lua_bin)
    state = load_state(args.state_path)
    state["overrides"] = regenerate(defaults, {}, state["custom"], args.custom_path)
    save_state(args.state_path, state)
    print(json.dumps({"ok": True}))


def _validate_custom(description: str, key: str, command: str):
    if not description.strip():
        return "Description can't be empty"
    if not key.strip():
        return "Key can't be empty"
    if not command.strip():
        return "Command can't be empty"
    return None


def cmd_add_custom(args):
    defaults = parse_defaults(args.hypr_path, args.lib_path, args.vars_path, args.lua_bin)
    state = load_state(args.state_path)
    description = args.description.strip()
    err = _validate_custom(description, args.key, args.command)
    if err:
        print(json.dumps({"ok": False, "error": err}))
        return
    existing_names = set(defaults.keys()) | {e["description"] for e in state["custom"].values()}
    if description in existing_names:
        print(json.dumps({"ok": False, "error": f"A keybind named '{description}' already exists"}))
        return
    cid = secrets.token_hex(4)
    state["custom"][cid] = {
        "description": description, "key": args.key.strip(), "command": args.command, "kind": args.kind,
    }
    state["overrides"] = regenerate(defaults, state["overrides"], state["custom"], args.custom_path)
    save_state(args.state_path, state)
    print(json.dumps({"ok": True, "id": cid}))


def cmd_update_custom(args):
    defaults = parse_defaults(args.hypr_path, args.lib_path, args.vars_path, args.lua_bin)
    state = load_state(args.state_path)
    if args.id not in state["custom"]:
        print(json.dumps({"ok": False, "error": "Unknown custom keybind"}))
        return
    description = args.description.strip()
    err = _validate_custom(description, args.key, args.command)
    if err:
        print(json.dumps({"ok": False, "error": err}))
        return
    existing_names = set(defaults.keys()) | {
        e["description"] for cid, e in state["custom"].items() if cid != args.id
    }
    if description in existing_names:
        print(json.dumps({"ok": False, "error": f"A keybind named '{description}' already exists"}))
        return
    kind = args.kind if args.kind else state["custom"][args.id].get("kind", "shell")
    state["custom"][args.id] = {
        "description": description, "key": args.key.strip(), "command": args.command, "kind": kind,
    }
    state["overrides"] = regenerate(defaults, state["overrides"], state["custom"], args.custom_path)
    save_state(args.state_path, state)
    print(json.dumps({"ok": True}))


def cmd_remove_custom(args):
    defaults = parse_defaults(args.hypr_path, args.lib_path, args.vars_path, args.lua_bin)
    state = load_state(args.state_path)
    state["custom"].pop(args.id, None)
    state["overrides"] = regenerate(defaults, state["overrides"], state["custom"], args.custom_path)
    save_state(args.state_path, state)
    print(json.dumps({"ok": True}))


def main():
    parser = argparse.ArgumentParser(description="Hyprland Lua keybind rebind manager")
    parser.add_argument("--hypr-path", default="$HOME/.config/hypr/hyprland/keybinds.lua")
    parser.add_argument("--lib-path", default="$HOME/.config/hypr/hyprland/lib/init.lua")
    parser.add_argument("--vars-path", default="$HOME/.config/hypr/hyprland/variables.lua")
    parser.add_argument("--custom-path", default="$HOME/.config/hypr/custom/keybinds.lua")
    parser.add_argument("--state-path", default="$HOME/.config/illogical-impulse/keybind-overrides.json")
    parser.add_argument("--lua-bin", default="lua5.4")
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("list")
    p_set = sub.add_parser("set")
    p_set.add_argument("description")
    p_set.add_argument("key")
    p_disable = sub.add_parser("disable")
    p_disable.add_argument("description")
    p_reset = sub.add_parser("reset")
    p_reset.add_argument("description")
    sub.add_parser("reset-all")
    p_add_custom = sub.add_parser("add-custom")
    p_add_custom.add_argument("description")
    p_add_custom.add_argument("key")
    p_add_custom.add_argument("command")
    p_add_custom.add_argument("--kind", choices=["shell", "lua"], default="shell")
    p_update_custom = sub.add_parser("update-custom")
    p_update_custom.add_argument("id")
    p_update_custom.add_argument("description")
    p_update_custom.add_argument("key")
    p_update_custom.add_argument("command")
    p_update_custom.add_argument("--kind", choices=["shell", "lua"], default=None)
    p_remove_custom = sub.add_parser("remove-custom")
    p_remove_custom.add_argument("id")

    args = parser.parse_args()
    args.hypr_path = expand(args.hypr_path)
    args.lib_path = expand(args.lib_path)
    args.vars_path = expand(args.vars_path)
    args.custom_path = expand(args.custom_path)
    args.state_path = expand(args.state_path)

    try:
        {
            "list": cmd_list, "set": cmd_set, "disable": cmd_disable,
            "reset": cmd_reset, "reset-all": cmd_reset_all,
            "add-custom": cmd_add_custom, "update-custom": cmd_update_custom,
            "remove-custom": cmd_remove_custom,
        }[args.cmd](args)
    except Exception as e:
        print(json.dumps({"ok": False, "error": str(e)}))
        sys.exit(1)


if __name__ == "__main__":
    main()
