#!/usr/bin/env python3
"""
Lets the shell manage custom Hyprland window rules (hl.window_rule()).

Rules are stored as JSON and (re)written as a clearly-marked, auto-generated
block appended to the end of custom/rules.lua - the user's own pre-existing
content in that file (and everything in hyprland/*.lua) is never touched.

The match/effect field schemas below are transcribed directly from
Hyprland's own source (src/desktop/rule/Rule.cpp's MATCH_PROP_STRINGS, and
src/config/lua/bindings/LuaBindingsInternal.hpp's WINDOW_RULE_EFFECT_DESCS)
at v0.56.2, so the set offered here matches exactly what hl.window_rule()
actually accepts.
"""
import argparse
import json
import os
import re
import secrets
import shutil
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

BEGIN_MARK = "-- ===== BEGIN illogical-impulse window rules (auto-generated by Settings > Window Rules; do not edit by hand) ====="
END_MARK = "-- ===== END illogical-impulse window rules ====="

# name -> value type: "bool" | "string" | "int" | "float" | "vec2"
# Each field maps to {"type": ..., + type-specific extras}. Types:
#   bool                     - toggle
#   string                   - free text
#   int/float                - slider; "min"/"max" are authoritative (from
#                              Hyprland's own CLuaConfigInt/Float bounds)
#                              when present, otherwise a practical default
#                              range (Hyprland itself doesn't bound them)
#   vec2                     - two expression fields (these accept formulas
#                              like "monitor_w*0.5", not just plain numbers)
#   enum                     - single choice, "options": [...]
#   enum_multi               - space-joined multi choice, "options": [...]
#   opacity                  - up to 3 alpha sliders (active/inactive/fullscreen)
#   intpair                  - two bounded int slots (fullscreen_state: internal/client)
FULLSCREEN_STATE_OPTIONS = ["none", "maximize", "fullscreen", "maximize+fullscreen"]

MATCH_FIELDS = {
    "class": {"type": "string"},
    "title": {"type": "string"},
    "initial_class": {"type": "string"},
    "initial_title": {"type": "string"},
    "float": {"type": "bool"},
    "tag": {"type": "string"},
    "xwayland": {"type": "bool"},
    "fullscreen": {"type": "bool"},
    "pin": {"type": "bool"},
    "focus": {"type": "bool"},
    "group": {"type": "bool"},
    "modal": {"type": "bool"},
    "fullscreen_state_internal": {"type": "enum", "options": FULLSCREEN_STATE_OPTIONS},
    "fullscreen_state_client": {"type": "enum", "options": FULLSCREEN_STATE_OPTIONS},
    "workspace": {"type": "string"},
    "content": {"type": "enum", "options": ["none", "photo", "video", "game"]},
    "xdg_tag": {"type": "string"},
    "namespace": {"type": "string"},
}

# Descriptions transcribed from the Hyprland wiki (Configuring/Basics/Window-Rules.md)
# and cross-checked against Rule.cpp's MATCH_PROP_STRINGS. Shown in Settings'
# field help popup - keep these accurate to the wiki, don't invent behavior.
MATCH_DESCRIPTIONS = {
    "class": "Match windows whose class matches this regular expression (RE2 syntax).",
    "title": "Match windows whose title matches this regular expression (RE2 syntax).",
    "initial_class": "Match windows whose initial (startup) class matches this regular expression. Unlike class, this never changes after the window opens.",
    "initial_title": "Match windows whose initial (startup) title matches this regular expression. Unlike title, this never changes after the window opens.",
    "float": "Match floating windows.",
    "tag": "Match windows that carry this tag (see the Tag effect, or check hyprctl clients).",
    "xwayland": "Match XWayland (X11) windows.",
    "fullscreen": "Match fullscreen windows (covering or non-covering).",
    "pin": "Match pinned windows.",
    "focus": "Match the currently focused window.",
    "group": "Match grouped windows.",
    "modal": "Match modal windows, e.g. \"Are you sure?\" confirmation popups.",
    "fullscreen_state_internal": "Match by Hyprland's own internal fullscreen state for the window.",
    "fullscreen_state_client": "Match by the fullscreen state the client itself requested (fullscreenClient in hyprctl clients).",
    "workspace": "Match windows on a given workspace. Accepts a workspace id, \"name:string\", or a workspace selector.",
    "content": "Match windows by their declared content type.",
    "xdg_tag": "Match windows by their xdgTag, if the app sets one (see hyprctl clients).",
    "namespace": "Match windows by namespace, the same field layer rules use (see hyprctl clients / hyprctl layers).",
}

EFFECT_FIELDS = {
    "float": {"type": "bool"},
    "tile": {"type": "bool"},
    "fullscreen": {"type": "bool"},
    "maximize": {"type": "bool"},
    "center": {"type": "bool"},
    "pseudo": {"type": "bool"},
    "no_initial_focus": {"type": "bool"},
    "pin": {"type": "bool"},
    "fullscreen_state": {"type": "intpair", "min": 0, "max": 3, "options": FULLSCREEN_STATE_OPTIONS},
    "move": {"type": "vec2"},
    "size": {"type": "vec2"},
    "monitor": {"type": "monitor"},
    "workspace": {"type": "string"},
    "group": {"type": "enum_multi", "options": ["set", "new", "lock", "invade", "barred", "deny", "override", "unset", "always"]},
    "suppress_event": {"type": "enum_multi", "options": ["fullscreen", "maximize", "activate", "activatefocus", "fullscreenoutput", "x11configurerequest"]},
    "content": {"type": "enum", "options": ["none", "photo", "video", "game"]},
    "no_close_for": {"type": "int", "min": 0, "max": 10000},
    "scrolling_width": {"type": "float", "min": 0.0, "max": 1.0},
    "rounding": {"type": "int", "min": 0, "max": 20},
    "border_size": {"type": "int", "min": 0, "max": 30},
    "rounding_power": {"type": "float", "min": 1.0, "max": 10.0},
    "scroll_mouse": {"type": "float", "min": 0.01, "max": 10.0},
    "scroll_touchpad": {"type": "float", "min": 0.01, "max": 10.0},
    "animation": {"type": "string"},
    "idle_inhibit": {"type": "enum", "options": ["none", "always", "focus", "fullscreen"]},
    "opacity": {"type": "opacity"},
    "tag": {"type": "string"},
    "max_size": {"type": "vec2"},
    "min_size": {"type": "vec2"},
    "border_color": {"type": "string"},  # hl accepts a plain string as a legacy fallback
    "persistent_size": {"type": "bool"},
    "allows_input": {"type": "bool"},
    "dim_around": {"type": "bool"},
    "decorate": {"type": "bool"},
    "focus_on_activate": {"type": "bool"},
    "keep_aspect_ratio": {"type": "bool"},
    "nearest_neighbor": {"type": "bool"},
    "no_anim": {"type": "bool"},
    "no_blur": {"type": "bool"},
    "no_dim": {"type": "bool"},
    "no_focus": {"type": "bool"},
    "no_follow_mouse": {"type": "bool"},
    "no_max_size": {"type": "bool"},
    "no_shadow": {"type": "bool"},
    "no_shortcuts_inhibit": {"type": "bool"},
    "opaque": {"type": "bool"},
    "force_rgbx": {"type": "bool"},
    "sync_fullscreen": {"type": "bool"},
    "immediate": {"type": "bool"},
    "xray": {"type": "bool"},
    "render_unfocused": {"type": "bool"},
    "no_screen_share": {"type": "bool"},
    "no_vrr": {"type": "bool"},
    "no_auto_hdr": {"type": "bool"},
    "stay_focused": {"type": "bool"},
    "confine_pointer": {"type": "bool"},
    "tonemap": {"type": "enum", "options": ["on", "off", "clamp", "limited"]},
}

# Descriptions transcribed from the Hyprland wiki (Configuring/Basics/Window-Rules.md).
# Shown in Settings' field help popup - keep these accurate to the wiki, don't invent behavior.
EFFECT_DESCRIPTIONS = {
    "float": "Floats the window.",
    "tile": "Tiles the window.",
    "fullscreen": "Fullscreens the window.",
    "maximize": "Maximizes the window.",
    "center": "If the window is floating, centers it on the monitor.",
    "pseudo": "Pseudotiles the window.",
    "no_initial_focus": "Disables the initial focus normally given to the window when it opens.",
    "pin": "Pins the window so it shows on all workspaces. Ignored for tiled windows - combine with Float.",
    "fullscreen_state": "Sets both the internal and client-requested fullscreen state.",
    "move": "Moves a floating window to a coordinate, monitor-local. Accepts plain numbers or expressions like monitor_w*0.5.",
    "size": "Resizes a floating window. Accepts plain numbers or expressions like monitor_w*0.5.",
    "monitor": "Sets the monitor the window should open on. \"Silent\" moves it without also switching your active monitor/workspace.",
    "workspace": "Sets the workspace the window should open on. Can also be \"unset\", or suffixed with \" silent\".",
    "group": "Sets window group behavior - see the option descriptions below.",
    "suppress_event": "Ignores the selected window events.",
    "content": "Sets the window's declared content type.",
    "no_close_for": "Makes the window uncloseable with killactive for this many milliseconds after it opens.",
    "scrolling_width": "Column width fraction for this window on a workspace using the scrolling layout.",
    "rounding": "Forces this many pixels of corner rounding, ignoring the theme default.",
    "border_size": "Sets the border size in pixels.",
    "rounding_power": "Overrides the corner rounding power/curve for the window.",
    "scroll_mouse": "Overrides input.scroll_factor for this window.",
    "scroll_touchpad": "Overrides input.touchpad.scroll_factor for this window.",
    "animation": "Forces an animation style onto the window, optionally with a speed percentage, e.g. \"popin 80%\".",
    "idle_inhibit": "Sets an idle-inhibit rule for the window.",
    "opacity": "Extra opacity multiplier for active/inactive/fullscreen. By default it multiplies the theme's opacity - toggle \"Absolute\" per slot to set an exact value instead.",
    "tag": "Applies a dynamic tag to the window. Prefix with + to add, - to remove, no prefix to toggle.",
    "max_size": "Maximum size for a floating window.",
    "min_size": "Minimum size for a floating window.",
    "border_color": "Forces the border color. Accepts a color or gradient string, e.g. rgb(FF0000) or rgba(33ccffee), and can list a second color/gradient for the inactive state.",
    "persistent_size": "Remembers this floating window's size (matched by class+title) and restores it the next time a window with the same class/title opens.",
    "allows_input": "Forces an XWayland window to receive input even if it asked not to.",
    "dim_around": "Dims everything around the window. Meant for floating windows.",
    "decorate": "Whether to draw window decorations.",
    "focus_on_activate": "Whether Hyprland focuses this window when it requests activation.",
    "keep_aspect_ratio": "Forces the aspect ratio to be kept when resizing with the mouse.",
    "nearest_neighbor": "Forces nearest-neighbor (pixelated) filtering for this window.",
    "no_anim": "Disables animations for the window.",
    "no_blur": "Disables blur for the window.",
    "no_dim": "Disables dimming for the window.",
    "no_focus": "Disables focus for the window entirely.",
    "no_follow_mouse": "Ignores input.follow_mouse for this window (won't focus on hover).",
    "no_max_size": "Removes max size limitations.",
    "no_shadow": "Disables shadows for the window.",
    "no_shortcuts_inhibit": "Disallows the app from inhibiting your keybinds.",
    "opaque": "Forces the window to be fully opaque. This overrides any Opacity rule regardless of order.",
    "force_rgbx": "Makes Hyprland ignore the window's alpha channel entirely.",
    "sync_fullscreen": "Keeps the fullscreen mode always in sync with what the client itself requested.",
    "immediate": "Forces the window to allow tearing.",
    "xray": "Sets blur xray mode for the window.",
    "render_unfocused": "Forces the window to think it's being rendered even when it's not visible.",
    "no_screen_share": "Hides the window (and its popups) from screen sharing by drawing black rectangles in their place.",
    "no_vrr": "Disables VRR for the window. Only effective when misc:vrr is set to 2 or 3.",
    "no_auto_hdr": "Disables AutoHDR for the window - useful to stop apps like foot triggering it when fullscreened.",
    "stay_focused": "Forces focus onto the window for as long as it's visible.",
    "confine_pointer": "Locks the mouse cursor to the window. Handy for keeping the cursor on one monitor while gaming.",
    "tonemap": "Controls HDR tonemapping behavior for the window.",
}

GROUP_OPTION_DESCRIPTIONS = [
    ("set [always]", "Open the window as a group."),
    ("new", "Shorthand for \"barred set\"."),
    ("lock [always]", "Lock the group. Combine with \"set\" or \"new\"."),
    ("barred", "Don't automatically group into the focused unlocked group."),
    ("deny", "Don't allow the window to be toggled as or added to a group."),
    ("invade", "Force-open the window in the locked group."),
    ("override [other options]", "Override other group rules."),
    ("unset", "Clear all group rules."),
]


def expand(path: str) -> str:
    return os.path.expanduser(os.path.expandvars(path))


def lua_quote(s: str) -> str:
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def lua_value(field: dict, value):
    t = field["type"]
    if t == "bool":
        return "true" if str(value).strip().lower() in ("1", "true", "yes", "on") else "false"
    if t == "int":
        return str(int(float(value)))
    if t == "float":
        return str(float(value))
    if t == "vec2":
        x, y = value
        return "{" + lua_quote(str(x)) + ", " + lua_quote(str(y)) + "}"
    if t == "enum_multi":
        tokens = value if isinstance(value, list) else [value]
        return lua_quote(" ".join(str(v) for v in tokens if v))
    if t == "opacity":
        tokens = value if isinstance(value, list) else [value]
        return lua_quote(" ".join(str(v) for v in tokens if v not in (None, "")))
    if t == "intpair":
        opts = field.get("options")
        a, b = value
        if opts:
            a = opts.index(a) if a in opts else 0
            b = opts.index(b) if b in opts else 0
        return lua_quote(f"{int(a)} {int(b)}")
    if t == "monitor":
        if isinstance(value, (list, tuple)):
            name, silent = (list(value) + [False])[:2]
        else:
            name, silent = value, False
        s = str(name)
        if silent:
            s += " silent"
        return lua_quote(s)
    return lua_quote(str(value))


def load_state(state_path: str) -> dict:
    if not os.access(state_path, os.R_OK):
        return {"rules": {}}
    try:
        with open(state_path, "r") as f:
            data = json.load(f)
    except (json.JSONDecodeError, OSError):
        return {"rules": {}}
    if not isinstance(data, dict) or not isinstance(data.get("rules"), dict):
        return {"rules": {}}
    return data


def save_state(state_path: str, state: dict):
    os.makedirs(os.path.dirname(state_path), exist_ok=True)
    with open(state_path, "w") as f:
        json.dump(state, f, indent=2, sort_keys=True)
        f.write("\n")


def strip_managed_block(content: str) -> str:
    pattern = re.compile(
        r"\n*" + re.escape(BEGIN_MARK) + r".*?" + re.escape(END_MARK) + r"\n*",
        re.DOTALL,
    )
    return pattern.sub("\n", content)


def validate_rule(rule: dict) -> str | None:
    match = rule.get("match") or []
    effects = rule.get("effects") or []
    if not match:
        return "A rule needs at least one match criterion"
    if not effects:
        return "A rule needs at least one effect"
    for m in match:
        if m.get("key") not in MATCH_FIELDS:
            return f"Unknown match field: {m.get('key')}"
    for e in effects:
        if e.get("key") not in EFFECT_FIELDS:
            return f"Unknown effect field: {e.get('key')}"
    return None


def regenerate(rules: dict, custom_path: str):
    body_parts = []
    for rid in sorted(rules.keys()):
        rule = rules[rid]
        if not rule.get("enabled", True):
            continue
        match = rule.get("match") or []
        effects = rule.get("effects") or []

        match_pairs = [f"{m['key']} = {lua_value(MATCH_FIELDS[m['key']], m['value'])}" for m in match]
        match_table = "{ " + ", ".join(match_pairs) + " }"

        effect_lines = [f"    {e['key']} = {lua_value(EFFECT_FIELDS[e['key']], e['value'])}," for e in effects]

        lines = [f"hl.window_rule({{  -- id:{rid}", f"    match = {match_table},"] + effect_lines + ["})"]
        body_parts.append("\n".join(lines))

    existing = ""
    if os.access(custom_path, os.R_OK):
        with open(custom_path, "r") as f:
            existing = f.read()
    stripped = strip_managed_block(existing).rstrip()

    if body_parts:
        block = BEGIN_MARK + "\n\n" + "\n\n".join(body_parts) + "\n\n" + END_MARK
        new_content = (stripped + "\n\n" + block + "\n") if stripped else (block + "\n")
    else:
        new_content = stripped + "\n" if stripped else ""

    os.makedirs(os.path.dirname(custom_path), exist_ok=True)
    if os.access(custom_path, os.R_OK):
        shutil.copyfile(custom_path, custom_path + ".bak")
    with open(custom_path, "w") as f:
        f.write(new_content)


def cmd_schema(args):
    print(json.dumps({
        "ok": True,
        "match": [{"key": k, "description": MATCH_DESCRIPTIONS.get(k, ""), **v} for k, v in MATCH_FIELDS.items()],
        "effects": [{"key": k, "description": EFFECT_DESCRIPTIONS.get(k, ""), **v} for k, v in EFFECT_FIELDS.items()],
        "groupOptions": [{"option": o, "description": d} for o, d in GROUP_OPTION_DESCRIPTIONS],
    }))


def cmd_list_monitors(args):
    try:
        monitors = json.loads(subprocess.run(
            ["hyprctl", "monitors", "-j"], capture_output=True, text=True, timeout=5,
        ).stdout)
    except Exception as e:
        print(json.dumps({"ok": False, "error": f"hyprctl monitors failed: {e}"}))
        return
    names = [m["name"] for m in monitors if m.get("name")]
    print(json.dumps({"ok": True, "monitors": names}))


def cmd_list_builtin(args):
    """Rules already defined directly in hyprland/rules.lua (the template
    file, overwritten on dots-hyprland updates) - shown read-only, since
    there's nothing safe to write a customization back to."""
    try:
        proc = subprocess.run(
            [args.lua_bin, args.extractor_path, args.hypr_path],
            capture_output=True, text=True, timeout=15,
        )
    except FileNotFoundError:
        print(json.dumps({"ok": False, "error": f"'{args.lua_bin}' interpreter not found"}))
        return
    except subprocess.TimeoutExpired:
        print(json.dumps({"ok": False, "error": "windowrule_extract.lua timed out"}))
        return
    try:
        data = json.loads(proc.stdout)
    except json.JSONDecodeError as e:
        print(json.dumps({"ok": False, "error": f"windowrule_extract.lua produced invalid JSON ({e}): {proc.stdout[:300]}"}))
        return
    if not data.get("ok"):
        print(json.dumps({"ok": False, "error": f"windowrule_extract.lua: {data.get('error')}"}))
        return

    rules = []
    for r in data["rules"]:
        match = [{"key": k, "value": v} for k, v in r["match"].items()]
        rules.append({"match": match, "effects": r["effects"]})
    print(json.dumps({"ok": True, "rules": rules}))


def cmd_list(args):
    state = load_state(args.state_path)
    rules = [{"id": rid, **rule} for rid, rule in state["rules"].items()]
    rules.sort(key=lambda r: r.get("createdAt", 0))
    print(json.dumps({"ok": True, "rules": rules}))


def cmd_add(args):
    state = load_state(args.state_path)
    rule = json.loads(args.rule_json)
    err = validate_rule(rule)
    if err:
        print(json.dumps({"ok": False, "error": err}))
        return
    rid = secrets.token_hex(4)
    import time
    rule["enabled"] = rule.get("enabled", True)
    rule["createdAt"] = time.time()
    state["rules"][rid] = rule
    regenerate(state["rules"], args.custom_path)
    save_state(args.state_path, state)
    print(json.dumps({"ok": True, "id": rid}))


def cmd_update(args):
    state = load_state(args.state_path)
    if args.id not in state["rules"]:
        print(json.dumps({"ok": False, "error": "Unknown rule"}))
        return
    rule = json.loads(args.rule_json)
    err = validate_rule(rule)
    if err:
        print(json.dumps({"ok": False, "error": err}))
        return
    rule["enabled"] = rule.get("enabled", True)
    rule["createdAt"] = state["rules"][args.id].get("createdAt", 0)
    state["rules"][args.id] = rule
    regenerate(state["rules"], args.custom_path)
    save_state(args.state_path, state)
    print(json.dumps({"ok": True}))


def cmd_set_enabled(args):
    state = load_state(args.state_path)
    if args.id not in state["rules"]:
        print(json.dumps({"ok": False, "error": "Unknown rule"}))
        return
    state["rules"][args.id]["enabled"] = args.enabled == "true"
    regenerate(state["rules"], args.custom_path)
    save_state(args.state_path, state)
    print(json.dumps({"ok": True}))


def cmd_remove(args):
    state = load_state(args.state_path)
    state["rules"].pop(args.id, None)
    regenerate(state["rules"], args.custom_path)
    save_state(args.state_path, state)
    print(json.dumps({"ok": True}))


def cmd_pick_window(args):
    """Lets the user click any window on screen, then matches the click
    point against hyprctl's window geometry. The settings window itself is
    a layer-shell surface (not a regular client hyprctl can move/hide) -
    losing it focus to slurp's own overlay while this runs is handled on
    the QML side (WindowRuleManager.pickingActive), not here."""
    try:
        clients = json.loads(subprocess.run(
            ["hyprctl", "clients", "-j"], capture_output=True, text=True, timeout=5,
        ).stdout)
    except Exception as e:
        print(json.dumps({"ok": False, "error": f"hyprctl clients failed: {e}"}))
        return

    try:
        proc = subprocess.run(
            ["slurp", "-p", "-f", "%x,%y"], capture_output=True, text=True, timeout=30,
        )
    except subprocess.TimeoutExpired:
        print(json.dumps({"ok": False, "error": "Timed out waiting for a click"}))
        return
    except FileNotFoundError:
        print(json.dumps({"ok": False, "error": "slurp is not installed"}))
        return

    if proc.returncode != 0 or not proc.stdout.strip():
        print(json.dumps({"ok": False, "error": "Cancelled"}))
        return

    try:
        x_str, y_str = proc.stdout.strip().split(",")
        x, y = float(x_str), float(y_str)
    except ValueError:
        print(json.dumps({"ok": False, "error": f"Could not parse slurp output: {proc.stdout!r}"}))
        return

    candidates = []
    for c in clients:
        if not c.get("mapped") or not c.get("visible"):
            continue
        ax, ay = c.get("at", [0, 0])
        w, h = c.get("size", [0, 0])
        if ax <= x < ax + w and ay <= y < ay + h:
            candidates.append(c)

    if not candidates:
        print(json.dumps({"ok": False, "error": "No window found at that point"}))
        return

    candidates.sort(key=lambda c: c.get("focusHistoryID", 999999))
    picked = candidates[0]
    print(json.dumps({
        "ok": True,
        "class": picked.get("class", ""),
        "title": picked.get("title", ""),
        "initialClass": picked.get("initialClass", ""),
        "initialTitle": picked.get("initialTitle", ""),
    }))


def main():
    parser = argparse.ArgumentParser(description="Hyprland custom window rule manager")
    parser.add_argument("--custom-path", default="$HOME/.config/hypr/custom/rules.lua")
    parser.add_argument("--state-path", default="$HOME/.config/illogical-impulse/windowrule-state.json")
    parser.add_argument("--hypr-path", default="$HOME/.config/hypr/hyprland/rules.lua")
    parser.add_argument("--extractor-path", default=os.path.join(SCRIPT_DIR, "windowrule_extract.lua"))
    parser.add_argument("--lua-bin", default="lua5.4")
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("schema")
    sub.add_parser("list")
    sub.add_parser("list-builtin")
    sub.add_parser("list-monitors")
    p_add = sub.add_parser("add")
    p_add.add_argument("rule_json")
    p_update = sub.add_parser("update")
    p_update.add_argument("id")
    p_update.add_argument("rule_json")
    p_set_enabled = sub.add_parser("set-enabled")
    p_set_enabled.add_argument("id")
    p_set_enabled.add_argument("enabled", choices=["true", "false"])
    p_remove = sub.add_parser("remove")
    p_remove.add_argument("id")
    sub.add_parser("pick-window")

    args = parser.parse_args()
    args.custom_path = expand(args.custom_path)
    args.hypr_path = expand(args.hypr_path)
    args.state_path = expand(args.state_path)

    try:
        {
            "schema": cmd_schema, "list": cmd_list, "list-builtin": cmd_list_builtin,
            "list-monitors": cmd_list_monitors,
            "add": cmd_add, "update": cmd_update,
            "set-enabled": cmd_set_enabled, "remove": cmd_remove, "pick-window": cmd_pick_window,
        }[args.cmd](args)
    except Exception as e:
        print(json.dumps({"ok": False, "error": str(e)}))
        sys.exit(1)


if __name__ == "__main__":
    main()
